import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import{readFileSync}from'node:fs';import{stripTypeScriptTypes}from'node:module';
const src=readFileSync(new URL('./rpc-manager.ts',import.meta.url),'utf8');const start=src.indexOf('      case "abort":');const body=src.slice(start,src.indexOf('      case "get_state":',start));const execute=vm.runInNewContext(stripTypeScriptTypes('(async function(){switch("abort"){'+body+'}})'),{DOMException,Promise,Error,console,randomUUID:()=>"notice",cancelSessionWakeups:()=>{}});
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return{resolve,reject,promise};};
const tick=()=>new Promise(r=>setImmediate(r));
function wrapper(){const sdk=deferred(),mcp=deferred(),ui=new AbortController(),controller=new AbortController();let signals=0,resets=0,running=true;const queue=['retained task'],notices=[];const object={emit:n=>notices.push(n),sessionId:'s',abortCleanupPromise:null,mcpPromptWait:{controller,done:mcp.promise},extensionUiAbortController:ui,forceShutdownOnIdle:false,inner:{abort:()=>{signals++;return sdk.promise;},clearQueue:()=>{throw Error('must preserve queue');}},isRunning:()=>running,resetIdleTimer:()=>resets++};return{object,sdk,mcp,ui,controller,queue,notices,get signals(){return signals;},get resets(){return resets;},idle:()=>running=false};}
test('Stop acknowledges while tools and MCP are pending, preserves queue, and owns one cleanup',async()=>{
 const h=wrapper(),ack=await execute.call(h.object);assert.equal(ack.accepted,true);assert.equal(h.signals,1);assert.equal(h.ui.signal.aborted,true);assert.equal(h.controller.signal.aborted,true);assert.equal(h.object.forceShutdownOnIdle,true);assert.equal(h.resets,0);
 const owner=h.object.abortCleanupPromise;await execute.call(h.object);assert.equal(h.signals,1);assert.equal(h.object.abortCleanupPromise,owner);assert.equal(h.queue[0],'retained task');h.sdk.resolve();await tick();assert.equal(h.resets,0,'MCP cleanup remains owned');h.idle();h.mcp.resolve();await owner;assert.equal(h.object.abortCleanupPromise,null);assert.equal(h.object.forceShutdownOnIdle,false);assert.equal(h.resets,1);
});
test('failed cleanup settles ownership and retains the guard while runtime is active',async()=>{const h=wrapper();await execute.call(h.object);const owner=h.object.abortCleanupPromise;h.sdk.reject(new Error('controlled failure'));h.mcp.resolve();await owner;assert.equal(h.object.forceShutdownOnIdle,true);assert.equal(h.object.abortCleanupPromise,null);assert.equal(h.resets,1);assert.equal(h.notices.length,1);assert.equal(h.notices[0].notifyType,"error");});
