/**
 * @file enhancement-settings.generated.ts
 * Automatically generated by pi-web-settings-prepaint helper from 02-plugin-registry-and-settings-schema.js.
 * Do not edit manually. Same canonical schema and fast reader algorithm.
 */

export interface EnhancementPluginMetadataItem {
  defaultEnabled: boolean;
  moduleId: string | null;
  moduleDefaultEnabled: boolean;
}

export type EnhancementPluginMetadataMap = Record<string, EnhancementPluginMetadataItem>;

export const ENHANCEMENT_METADATA: EnhancementPluginMetadataMap = {
  "stop-fast-response": {
    "defaultEnabled": true,
    "moduleId": "composer-workflow",
    "moduleDefaultEnabled": true
  },
  "user-message-reconcile": {
    "defaultEnabled": true,
    "moduleId": "conversation-navigation",
    "moduleDefaultEnabled": true
  },
  "general-settings-dashboard": {
    "defaultEnabled": true,
    "moduleId": "local-workspace",
    "moduleDefaultEnabled": true
  },
  "model-generation-speed": {
    "defaultEnabled": true,
    "moduleId": "task-insights",
    "moduleDefaultEnabled": true
  },
  "turn-duration": {
    "defaultEnabled": true,
    "moduleId": "task-insights",
    "moduleDefaultEnabled": true
  },
  "turn-number-indicator": {
    "defaultEnabled": true,
    "moduleId": "task-insights",
    "moduleDefaultEnabled": true
  },
  "task-tool-auto-collapse": {
    "defaultEnabled": true,
    "moduleId": "conversation-navigation",
    "moduleDefaultEnabled": true
  },
  "tool-card-layout-stability": {
    "defaultEnabled": true,
    "moduleId": "conversation-navigation",
    "moduleDefaultEnabled": true
  },
  "subagent-dispatch-cards": {
    "defaultEnabled": true,
    "moduleId": "conversation-navigation",
    "moduleDefaultEnabled": true
  },
  "subagent-model-override": {
    "defaultEnabled": true,
    "moduleId": "subagent-dispatch",
    "moduleDefaultEnabled": true
  },
  "history-scroll-stability": {
    "defaultEnabled": true,
    "moduleId": "conversation-navigation",
    "moduleDefaultEnabled": true
  },
  "session-scroll-restore": {
    "defaultEnabled": true,
    "moduleId": "conversation-navigation",
    "moduleDefaultEnabled": true
  },
  "session-virtual-scroll": {
    "defaultEnabled": true,
    "moduleId": "conversation-navigation",
    "moduleDefaultEnabled": true
  },
  "compaction-auto-collapse": {
    "defaultEnabled": true,
    "moduleId": "conversation-navigation",
    "moduleDefaultEnabled": true
  },
  "pi-mail-auto-collapse": {
    "defaultEnabled": true,
    "moduleId": "conversation-navigation",
    "moduleDefaultEnabled": true
  },
  "live-stopwatch": {
    "defaultEnabled": true,
    "moduleId": "task-insights",
    "moduleDefaultEnabled": true
  },
  "model-scope-warning": {
    "defaultEnabled": true,
    "moduleId": "safety-performance",
    "moduleDefaultEnabled": true
  },
  "quick-quote": {
    "defaultEnabled": true,
    "moduleId": "selection-context",
    "moduleDefaultEnabled": true
  },
  "settings-tab-shortcuts": {
    "defaultEnabled": true,
    "moduleId": "session-sidebar",
    "moduleDefaultEnabled": true
  },
  "context-menu": {
    "defaultEnabled": true,
    "moduleId": "session-sidebar",
    "moduleDefaultEnabled": true
  },
  "thinking-persistence": {
    "defaultEnabled": true,
    "moduleId": "preference-memory",
    "moduleDefaultEnabled": true
  },
  "enhancement-settings-archive": {
    "defaultEnabled": true,
    "moduleId": "preference-memory",
    "moduleDefaultEnabled": true
  },
  "chat-scrollbar": {
    "defaultEnabled": true,
    "moduleId": "conversation-navigation",
    "moduleDefaultEnabled": true
  },
  "native-message-font": {
    "defaultEnabled": true,
    "moduleId": "conversation-navigation",
    "moduleDefaultEnabled": true
  },
  "turn-usage-total": {
    "defaultEnabled": true,
    "moduleId": "task-insights",
    "moduleDefaultEnabled": true
  },
  "minimap-full-nav": {
    "defaultEnabled": true,
    "moduleId": "conversation-navigation",
    "moduleDefaultEnabled": true
  },
  "esc-guard": {
    "defaultEnabled": true,
    "moduleId": "safety-performance",
    "moduleDefaultEnabled": true
  },
  "mobile-enter-newline": {
    "defaultEnabled": true,
    "moduleId": "composer-workflow",
    "moduleDefaultEnabled": true
  },
  "mobile-model-keyboard-guard": {
    "defaultEnabled": true,
    "moduleId": "composer-workflow",
    "moduleDefaultEnabled": true
  },
  "composer-clean-placeholder": {
    "defaultEnabled": true,
    "moduleId": "composer-workflow",
    "moduleDefaultEnabled": true
  },
  "ask-user-web-native": {
    "defaultEnabled": true,
    "moduleId": "ask-user-experience",
    "moduleDefaultEnabled": true
  },
  "project-status-indicator": {
    "defaultEnabled": true,
    "moduleId": "background-attention",
    "moduleDefaultEnabled": true
  },
  "session-attention-sound": {
    "defaultEnabled": true,
    "moduleId": "background-attention",
    "moduleDefaultEnabled": true
  },
  "session-attention-desktop": {
    "defaultEnabled": false,
    "moduleId": "background-attention",
    "moduleDefaultEnabled": true
  },
  "ask-user-batch-prototype": {
    "defaultEnabled": false,
    "moduleId": "ask-user-experience",
    "moduleDefaultEnabled": true
  },
  "quick-action-buttons": {
    "defaultEnabled": false,
    "moduleId": "composer-workflow",
    "moduleDefaultEnabled": true
  },
  "empty-send-continue": {
    "defaultEnabled": true,
    "moduleId": "composer-workflow",
    "moduleDefaultEnabled": true
  },
  "scroll-to-bottom": {
    "defaultEnabled": true,
    "moduleId": "conversation-navigation",
    "moduleDefaultEnabled": true
  },
  "local-path-launcher": {
    "defaultEnabled": true,
    "moduleId": "local-workspace",
    "moduleDefaultEnabled": true
  },
  "session-history-integrity": {
    "defaultEnabled": false,
    "moduleId": "local-workspace",
    "moduleDefaultEnabled": true
  },
  "session-history-order-guard": {
    "defaultEnabled": true,
    "moduleId": "local-workspace",
    "moduleDefaultEnabled": true
  },
  "session-memory-cache": {
    "defaultEnabled": true,
    "moduleId": "local-workspace",
    "moduleDefaultEnabled": true
  },
  "usage-cost-dashboard": {
    "defaultEnabled": true,
    "moduleId": "task-insights",
    "moduleDefaultEnabled": true
  },
  "cross-device-session-sync": {
    "defaultEnabled": true,
    "moduleId": "local-workspace",
    "moduleDefaultEnabled": true
  },
  "code-block-scan-guard": {
    "defaultEnabled": true,
    "moduleId": "safety-performance",
    "moduleDefaultEnabled": true
  },
  "session-pin-archive": {
    "defaultEnabled": true,
    "moduleId": "session-sidebar",
    "moduleDefaultEnabled": true
  },
  "session-section-headers": {
    "defaultEnabled": true,
    "moduleId": "session-sidebar",
    "moduleDefaultEnabled": true
  },
  "session-model-label": {
    "defaultEnabled": true,
    "moduleId": "session-sidebar",
    "moduleDefaultEnabled": true
  },
  "session-item-compact": {
    "defaultEnabled": true,
    "moduleId": "session-sidebar",
    "moduleDefaultEnabled": true
  },
  "session-color": {
    "defaultEnabled": true,
    "moduleId": "session-sidebar",
    "moduleDefaultEnabled": true
  },
  "session-tags": {
    "defaultEnabled": true,
    "moduleId": "session-sidebar",
    "moduleDefaultEnabled": true
  },
  "session-odoo-addons": {
    "defaultEnabled": true,
    "moduleId": "session-sidebar",
    "moduleDefaultEnabled": true
  },
  "session-dblclick-rename": {
    "defaultEnabled": true,
    "moduleId": "session-sidebar",
    "moduleDefaultEnabled": true
  },
  "composer-draft-cache": {
    "defaultEnabled": true,
    "moduleId": "composer-workflow",
    "moduleDefaultEnabled": true
  },
  "composer-file-paste": {
    "defaultEnabled": true,
    "moduleId": "composer-workflow",
    "moduleDefaultEnabled": true
  },
  "session-search-shortcut": {
    "defaultEnabled": true,
    "moduleId": "session-sidebar",
    "moduleDefaultEnabled": true
  },
  "session-search-project-folding": {
    "defaultEnabled": true,
    "moduleId": "session-sidebar",
    "moduleDefaultEnabled": true
  },
  "mobile-swipe-drawer": {
    "defaultEnabled": true,
    "moduleId": "session-sidebar",
    "moduleDefaultEnabled": true
  },
  "composer-image-zoom": {
    "defaultEnabled": true,
    "moduleId": "composer-workflow",
    "moduleDefaultEnabled": true
  },
  "codex-composer-layout": {
    "defaultEnabled": true,
    "moduleId": "composer-workflow",
    "moduleDefaultEnabled": true
  },
  "composer-model-reasoning-pill": {
    "defaultEnabled": true,
    "moduleId": "composer-workflow",
    "moduleDefaultEnabled": true
  },
  "running-model-switch": {
    "defaultEnabled": true,
    "moduleId": "composer-workflow",
    "moduleDefaultEnabled": true
  },
  "composer-queue-panel": {
    "defaultEnabled": true,
    "moduleId": "composer-workflow",
    "moduleDefaultEnabled": true
  },
  "composer-format-toggle": {
    "defaultEnabled": false,
    "moduleId": "composer-workflow",
    "moduleDefaultEnabled": true
  },
  "composer-compact-button": {
    "defaultEnabled": false,
    "moduleId": "composer-workflow",
    "moduleDefaultEnabled": true
  },
  "composer-tool-preset": {
    "defaultEnabled": false,
    "moduleId": "composer-workflow",
    "moduleDefaultEnabled": true
  },
  "composer-markdown-format": {
    "defaultEnabled": true,
    "moduleId": "composer-workflow",
    "moduleDefaultEnabled": true
  },
  "composer-modes": {
    "defaultEnabled": true,
    "moduleId": "composer-workflow",
    "moduleDefaultEnabled": true
  },
  "at-mention-plugins": {
    "defaultEnabled": true,
    "moduleId": "composer-workflow",
    "moduleDefaultEnabled": true
  },
  "image-dblclick-preview": {
    "defaultEnabled": true,
    "moduleId": "conversation-navigation",
    "moduleDefaultEnabled": true
  },
  "session-panel-binding": {
    "defaultEnabled": true,
    "moduleId": "local-workspace",
    "moduleDefaultEnabled": true
  },
  "file-panel-overlay-guard": {
    "defaultEnabled": true,
    "moduleId": "local-workspace",
    "moduleDefaultEnabled": true
  },
  "client-crash-diagnostics": {
    "defaultEnabled": true,
    "moduleId": "safety-performance",
    "moduleDefaultEnabled": true
  },
  "streaming-thinking-guard": {
    "defaultEnabled": true,
    "moduleId": "safety-performance",
    "moduleDefaultEnabled": true
  },
  "notification-center": {
    "defaultEnabled": true,
    "moduleId": "notification-management",
    "moduleDefaultEnabled": true
  },
  "obsidian-markdown-viewer": {
    "defaultEnabled": true,
    "moduleId": "local-workspace",
    "moduleDefaultEnabled": true
  },
  "excel-sheet-preview": {
    "defaultEnabled": true,
    "moduleId": "local-workspace",
    "moduleDefaultEnabled": true
  },
  "workspace-picker-hover": {
    "defaultEnabled": true,
    "moduleId": "local-workspace",
    "moduleDefaultEnabled": true
  },
  "session-batch-actions": {
    "defaultEnabled": true,
    "moduleId": "session-sidebar",
    "moduleDefaultEnabled": true
  },
  "pi-agent-update-notice": {
    "defaultEnabled": true,
    "moduleId": "task-insights",
    "moduleDefaultEnabled": true
  },
  "pi-web-plus-branding": {
    "defaultEnabled": true,
    "moduleId": "local-workspace",
    "moduleDefaultEnabled": true
  }
};

export type StorageGetter = (key: string) => string | null | undefined;

export function createFastPluginReader(
  storageGetter: StorageGetter,
  metadata: EnhancementPluginMetadataMap = ENHANCEMENT_METADATA
): (pluginId: string) => boolean {
  let lastRaw: string | null | undefined;
  let parsedModern: {
    modules?: Record<string, { enabled?: boolean }>;
    features?: Record<string, { enabled?: boolean }>;
  } | null = null;

  const read = (key: string): string | null => {
    try {
      const value = storageGetter(key);
      return value === undefined ? null : value;
    } catch (_) {
      return null;
    }
  };

  return function isPluginFastActive(pluginId: string): boolean {
    if (!Object.prototype.hasOwnProperty.call(metadata, pluginId)) return true;
    const info = metadata[pluginId];
    const raw = read("pi-enh-settings-v1");
    if (raw !== lastRaw) {
      lastRaw = raw;
      parsedModern = null;
      if (raw) {
        try {
          parsedModern = JSON.parse(raw);
        } catch (_) {}
      }
    }

    const moduleConfig = parsedModern && parsedModern.modules && parsedModern.modules[info.moduleId!];
    const moduleEnabled =
      moduleConfig && typeof moduleConfig.enabled === "boolean"
        ? moduleConfig.enabled
        : info.moduleDefaultEnabled;

    if (info.moduleId && !moduleEnabled) return false;

    if (parsedModern) {
      const feature = parsedModern.features && parsedModern.features[pluginId];
      return feature && typeof feature.enabled === "boolean"
        ? feature.enabled
        : info.defaultEnabled;
    }

    const legacy = read("pi-enh-plugin-" + pluginId);
    return legacy === null ? info.defaultEnabled : legacy === "true";
  };
}

const defaultReader = createFastPluginReader((key: string) => {
  if (typeof window === "undefined" || !window.localStorage) return null;
  try {
    return window.localStorage.getItem(key);
  } catch (_) {
    return null;
  }
});

export function isEnhancementPluginFastActive(
  pluginId: string,
  storageGetter?: StorageGetter
): boolean {
  if (storageGetter) {
    return createFastPluginReader(storageGetter, ENHANCEMENT_METADATA)(pluginId);
  }
  return defaultReader(pluginId);
}
