const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),test=require('node:test'),ts=require('typescript');
const source=fs.readFileSync(__dirname+'/useIsMobile.ts','utf8');
function fixture({mobile=false,coarse=false,connected=true,focused=false,ssr=false}={}){let calls=0;const doc={activeElement:null},el={isConnected:connected,focus(){calls++;doc.activeElement=el}};if(focused)doc.activeElement=el;const module={exports:{}};vm.runInNewContext(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{module,exports:module.exports,require:()=>({}),document:doc,...(!ssr?{window:{matchMedia:q=>({matches:q.includes('coarse')?coarse:mobile})}}:{})});return{...module.exports,el,calls:()=>calls};}
for(const [name,options,expected]of [['phone portrait',{mobile:true},false],['phone landscape',{coarse:true},false],['desktop',{},true],['unmounted desktop',{connected:false},false],['server render',{ssr:true},false]])test(name,()=>{const f=fixture(options);assert.equal(f.focusEditable(f.el),expected);assert.equal(f.calls(),expected?1:0)});
test('phone preserves direct user focus without a second focus call',()=>{const f=fixture({mobile:true,focused:true});assert.equal(f.focusEditable(f.el),true);assert.equal(f.calls(),0)});
test('absent editor cannot request focus',()=>{const f=fixture();assert.equal(f.focusEditable(null),false);assert.equal(f.calls(),0)});
const enhancement=fs.readFileSync(__dirname+'/../enhancements/modules/05-composer-and-input-workflow.js','utf8');
const ast=ts.createSourceFile('module.js',enhancement,ts.ScriptTarget.Latest,true,ts.ScriptKind.JS);function find(name){let result;function visit(n){if(ts.isFunctionDeclaration(n)&&n.name?.text===name)result=n;ts.forEachChild(n,visit)}visit(ast);assert(result);return result.getText(ast)}
test('enhancement delegates focus to native owner',()=>{let calls=0;const ctx={readNativeComposerDraft:()=>({handle:{focusEditable(){calls++;return false}}}),isMobileEnvironment:()=>true};vm.createContext(ctx);vm.runInContext(find('focusComposerEditable'),ctx);assert.equal(ctx.focusComposerEditable({force:true}),false);assert.equal(calls,1)});
test('old mobile fallback cannot focus an editor',()=>{const ctx={readNativeComposerDraft:()=>null,isMobileEnvironment:()=>true,findActiveComposerEditable:()=>{throw Error('must not find/focus')}};vm.createContext(ctx);vm.runInContext(find('focusComposerEditable'),ctx);assert.equal(ctx.focusComposerEditable({force:true}),false)});
test('mobile new-session path schedules no focus retry',()=>{const ctx={isMobileEnvironment:()=>true,requestAnimationFrame:()=>{throw Error('must not retry')}};vm.createContext(ctx);vm.runInContext(find('triggerNewSessionComposerFocus'),ctx);ctx.triggerNewSessionComposerFocus()});
