const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(__dirname+'/../modules/05-composer-and-input-workflow.js','utf8');
const start=source.indexOf('  async function executeBatchDeleteSessions('),end=source.indexOf('\n  // 鼠标点击捕获监听',start);
function fixture(payload,error){const cleaned=[],restored=[],notified=[],requests=[],refreshes=[];const selectedSessionBatchIds=new Set(["a","b"]),rerenders=[];const c={console,Map,Set,Array,AbortController,setTimeout,clearTimeout,batchDeleteInFlight:false,selectedSessionBatchIds,syncSessionBatchBar(){},window:{__PI_ENH_RERENDER_SESSIONS__:()=>rerenders.push(1),history:{replaceState(){}},__PI_ENH_SESSION_DELETED__:id=>notified.push(id)},getCurrentSessionId:()=> 'b',markSessionAsDeleted(){},getSessionRowById:()=>null,syncSessionBatchRowStates(){},fetch:async(url,options)=>{requests.push({url,options});if(error)throw error;return{ok:true,json:async()=>payload}},markSessionDeleteConfirmed(){},cleanupDeletedSessionEverywhere:id=>cleaned.push(id),cleanupSessionUploadedFiles:async()=>{},restoreSessionDeleteState:id=>restored.push(id),requestSessionListRefresh:()=>refreshes.push(1),closeBatchDeleteModal(){},setSessionBatchMode(){},showToast(){},sessionDeleteIcon:''};vm.runInNewContext(source.slice(start,end)+'\nthis.run=executeBatchDeleteSessions;',c);return{c,cleaned,restored,notified,requests,refreshes,rerenders};}
test('batch uses one request and cleans successful/cascade IDs once; failed active session is retained',async()=>{const f=fixture({results:[{id:'a',ok:true},{id:'b',ok:false}],deletedSessionIds:['a','child']});await f.c.run(['a','b'],{});assert.equal(f.requests.length,1);assert.equal(f.requests[0].url,'/api/sessions/batch-delete');assert.deepEqual(f.cleaned,['a','child']);assert.deepEqual(f.restored,['b']);assert.deepEqual(f.notified,['a','child']);assert.equal(f.refreshes.length,1);});
test('transport failure restores all targets without pretending they were deleted',async()=>{const f=fixture(null,Error('offline'));await f.c.run(['a','b'],{});assert.deepEqual(f.cleaned,[]);assert.deepEqual(f.restored,['a','b']);assert.equal(f.refreshes.length,1);});

test('failed selections remain available for retry; batch pending state releases',async()=>{const f=fixture({results:[{id:'a',ok:true},{id:'b',ok:false}],deletedSessionIds:['a']});await f.c.run(['a','b'],{});assert.deepEqual([...f.c.selectedSessionBatchIds],['b']);assert.equal(f.c.batchDeleteInFlight,false);assert.equal(f.rerenders.length,2);});
test('transport failure stops remaining batches and sends no automatic retry',async()=>{const f=fixture(null,Error('offline'));const ids=Array.from({length:101},(_,i)=>'id'+i);await f.c.run(ids,{});assert.equal(f.requests.length,1);assert.equal(f.restored.length,101);assert.equal(f.c.selectedSessionBatchIds.size,101);assert.equal(f.c.batchDeleteInFlight,false);});
test('double confirmation is ignored while original batch awaits receipt',async()=>{const f=fixture({results:[{id:'a',ok:true}],deletedSessionIds:['a']});const first=f.c.run(['a'],{});await f.c.run(['a'],{});await first;assert.equal(f.requests.length,1);});
test('request deadline releases pending state without inventing a deletion receipt',async()=>{const f=fixture();f.c.setTimeout=(fn,ms)=>setTimeout(fn,ms===30000?5:ms);f.c.fetch=async(u,o)=>new Promise((resolve,reject)=>o.signal.addEventListener('abort',()=>reject(Error('deadline'))));await f.c.run(['a'],{});assert.deepEqual(f.cleaned,[]);assert.deepEqual(f.restored,['a']);assert.equal(f.c.batchDeleteInFlight,false);assert.deepEqual([...f.c.selectedSessionBatchIds],['a']);});
