const {chromium}=require('playwright'),fs=require('fs'),a=require('node:assert/strict');
const origin=process.env.PI_WEB_BATCH_TEST_ORIGIN,cwd=process.env.PI_WEB_BATCH_TEST_CWD;
if(!origin||!cwd)throw Error('Use an owned isolated server and 13 owned fixture sessions; set PI_WEB_BATCH_TEST_ORIGIN and PI_WEB_BATCH_TEST_CWD');
const url=new URL(origin);a(['127.0.0.1','localhost'].includes(url.hostname)&&!['30141','30142','30143','80','443',''].includes(url.port),'Production target forbidden');a(cwd.includes('/discovery-fixture/'),'Owned fixture root required');
const artifacts=process.env.PI_WEB_BATCH_TEST_OUTPUT||__dirname;fs.mkdirSync(artifacts,{recursive:true});const out={checks:[],errors:[]};
(async()=>{const b=await chromium.launch({headless:true,args:['--no-sandbox']});const watchdog=setTimeout(()=>{fs.writeFileSync(artifacts+'/browser-deadline.json',JSON.stringify(out,null,2));b.close();setTimeout(()=>process.exit(1),1500)},45000);try{const catalogue=await (await b.newContext()).request.get(origin+'/api/sessions?force=1');const ids=(await catalogue.json()).sessions.map(s=>s.id);a.equal(ids.length,13);a(ids.every(id=>id.startsWith('11111111-1111-4111-8111-')),'Only isolated fixture sessions may be deleted');
for(const [name,width,mode]of [['mobile-partial',390,'partial'],['mobile-network',390,'offline'],['desktop-slow-real',1280,'real']]){out.stage=name;const c=await b.newContext({viewport:{width,height:width===390?844:900},locale:'zh-CN',isMobile:width===390,hasTouch:width===390});await c.addInitScript(()=>{localStorage.setItem('pi-locale','zh-CN');localStorage.setItem('pi-theme','dark')});let requests=0,responsePayload;await c.route('**/api/sessions/batch-delete',async r=>{requests++;const data=r.request().postDataJSON();a(data.ids.every(id=>ids.includes(id)));if(mode==='offline')return r.abort('failed');if(mode==='partial')return r.fulfill({json:{results:data.ids.map((id,i)=>({id,ok:i===0})),deletedSessionIds:[data.ids[0]]}});await new Promise(resolve=>setTimeout(resolve,700));return r.continue();});const p=await c.newPage();p.on('pageerror',e=>out.errors.push(e.message));p.on('response',async r=>{if(r.url().endsWith('/api/sessions/batch-delete')&&mode==='real')responsePayload=await r.json()});await p.goto(origin+'/?cwd='+encodeURIComponent(cwd),{waitUntil:'load'});await p.locator('.pi-enh-session-row-host').first().waitFor({state:'attached',timeout:8000});if((await p.locator('#pi-enh-session-batch-btn').boundingBox()).x<0){const buttons=await p.locator('button').evaluateAll(bs=>bs.filter(x=>/sidebar|侧栏|侧边/.test((x.title||'')+' '+(x.getAttribute('aria-label')||''))).map(x=>({title:x.title,aria:x.getAttribute('aria-label')})));out.mobileButtons=buttons;const toggle=p.locator('button[title*="sidebar"],button[aria-label*="sidebar"],button[title*="侧栏"],button[aria-label*="侧栏"],button[title="显示侧边栏"]').first();await toggle.click({timeout:3000});}
await p.locator('#pi-enh-session-batch-btn').click();await p.locator('#pi-enh-session-batch-bar input').check({timeout:3000});a.equal((await p.evaluate(()=>window.__PI_ENH_GET_SELECTED_BATCH_SESSION_IDS__())).length,13);
await p.evaluate(()=>{window.__batchTestNode=document.querySelector('#pi-enh-session-batch-bar input');window.__batchTestFrames=0;window.__batchTestStop=false;const tick=()=>{window.__batchTestFrames++;if(!window.__batchTestStop)requestAnimationFrame(tick)};requestAnimationFrame(tick);});await p.locator('#pi-enh-session-batch-bar [data-action="batch-delete"]').click();await p.locator('#pi-enh-batch-delete-modal').waitFor();await p.screenshot({path:artifacts+'/'+name+'-before.png'});const start=Date.now();await p.locator('#pi-enh-batch-delete-modal [data-action="confirm"]').click({timeout:3000});await p.locator('#pi-enh-batch-delete-modal').waitFor({state:'detached',timeout:8000});const elapsed=Date.now()-start;
const state=await p.evaluate(()=>{window.__batchTestStop=true;return{selected:window.__PI_ENH_GET_SELECTED_BATCH_SESSION_IDS__(),batch:window.__PI_ENH_IS_SESSION_BATCH_MODE__(),frames:window.__batchTestFrames,nodeStable:window.__batchTestNode===document.querySelector('#pi-enh-session-batch-bar input'),overflow:document.documentElement.scrollWidth>innerWidth,textareaEnabled:!!document.querySelector('[data-pi-native-composer-host] textarea:not(:disabled)')}});a.equal(requests,1);a(state.frames>1&&state.textareaEnabled&&!state.overflow);if(mode==='real'){a.equal(state.batch,false);a.equal(state.selected.length,0);a.equal(responsePayload.results.length,13);a(responsePayload.results.every(x=>x.ok));a.equal(responsePayload.deletedSessionIds.length,13);const after=await (await c.request.get(origin+'/api/sessions?force=1')).json();a.equal(after.sessions.length,0);}else {a.equal(state.batch,true);a.equal(state.selected.length,mode==='partial'?12:13);a(state.nodeStable,'Toolbar checkbox identity must survive all sidebar updates');await p.locator('#pi-enh-session-batch-bar input').uncheck();a.equal((await p.evaluate(()=>window.__PI_ENH_GET_SELECTED_BATCH_SESSION_IDS__())).length,0);}
await p.screenshot({path:artifacts+'/'+name+'-after.png'});out.checks.push({name,viewport:{width,height:width===390?844:900},mode,requests,elapsedMs:elapsed,state});await c.close();}a.equal(out.errors.length,0);out.status='passed';}catch(e){out.status='failed';out.failure=e.message;process.exitCode=1;}finally{clearTimeout(watchdog);await b.close();fs.writeFileSync(artifacts+'/browser.json',JSON.stringify(out,null,2));console.log(JSON.stringify(out));}})();
