const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const R=process.env.CANDIDATE_SOURCE||require('node:path').resolve(__dirname,'../..');
function loader(demand=false){const nodes=[];const root={Map,Promise,setTimeout,clearTimeout,__PI_IMAGE_PRELOAD_REQUESTED__:demand,document:{createElement:()=>({dataset:{},remove(){}}),head:{appendChild:n=>nodes.push(n)}}};root.window=root;vm.runInNewContext(fs.readFileSync(R+'/enhancements/lazy-assets.js','utf8').replace('__PI_OPTIONAL_ASSET_MANIFEST__',JSON.stringify({'image-editor':{path:'/editor.js',integrity:'sha256-image'}})),root);return {root,nodes};}
test('image demand queued before loader starts exactly one request and shares subsequent opens',async()=>{const f=loader(true);assert.equal(f.nodes.length,1);const a=f.root.__PI_ENH_LOAD_OPTIONAL__('image-editor'),b=f.root.__PI_ENH_LOAD_OPTIONAL__('image-editor');assert.equal(a,b);f.root.PiImageEditor={create(){}};f.nodes[0].onload();await a;assert.equal(f.nodes.length,1);});
test('without image demand optional editor remains cold',()=>{assert.equal(loader().nodes.length,0)});
function scheduler({state='loading',hidden=false,safari=false}={}){const events=new Map(),idle=new Map(),timers=new Map();let requests=0,n=0;const doc={readyState:state,visibilityState:hidden?'hidden':'visible',addEventListener:(e,cb)=>events.set(e,cb),removeEventListener:(e,cb)=>{if(events.get(e)===cb)events.delete(e)}};const win={addEventListener:doc.addEventListener,removeEventListener:doc.removeEventListener,...(!safari?{requestIdleCallback:cb=>{idle.set(++n,cb);return n},cancelIdleCallback:id=>idle.delete(id)}:{})};const code=fs.readFileSync(R+'/lib/image-capabilities.ts','utf8').split('// Keep image work')[1];const ctx={document:doc,window:win,setTimeout:cb=>{timers.set(++n,cb);return n},clearTimeout:id=>timers.delete(id),preloadImageCapabilities:()=>requests++};vm.runInNewContext(require('esbuild').transformSync('// Keep image work'+code,{loader:'ts',format:'cjs'}).code.replace(/module\.exports = __toCommonJS\(stdin_exports\);/,'' )+'\nthis.schedule=scheduleImagePreload;',ctx);return {ctx,events,idle,timers,doc,requests:()=>requests};}
test('idle waits for page load; cancellation removes scheduled work',()=>{const f=scheduler();const cancel=f.ctx.schedule();assert.equal(f.idle.size,0);f.events.get('load')();assert.equal(f.idle.size,1);cancel();assert.equal(f.idle.size,0);assert.equal(f.requests(),0)});
test('hidden pages wait until visible and schedule only once',()=>{const f=scheduler({state:'complete',hidden:true});f.ctx.schedule();assert.equal(f.idle.size,0);f.doc.visibilityState='visible';f.events.get('visibilitychange')();assert.equal(f.events.has('visibilitychange'),false);[...f.idle.values()][0]();assert.equal(f.requests(),1)});
test('Safari uses a cancellable one-shot fallback',()=>{const f=scheduler({state:'complete',safari:true});const cancel=f.ctx.schedule();assert.equal(f.timers.size,1);[...f.timers.values()][0]();assert.equal(f.requests(),1);cancel();assert.equal(f.timers.size,0)});
